name: acute_university
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.7



  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#004ADD"
  image: images/img.png


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - assets/


  fonts:
    - family: Sansation
      fonts:
         - asset: assets/sansation/Sansation_Bold.ttf
         - asset: assets/sansation/Sansation_Regular.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
